apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-stats-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: oss-static-pv-stats
  storageClassName: ""  
