name: Build, Push & Deploy to OpenShift

on:
  push:
    branches: [main, dev, Automation]
  pull_request:
    branches: [main, dev, Automation]

jobs:
  deploy:
    runs-on: [self-hosted]

    env:
      REGISTRY: ghcr.io

    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning workspace..."
          rm -rf * .??* || true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from version.txt
        id: version
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Branch: $BRANCH"

          MAIN_VERSION=$(grep "^version_main:" version.txt | awk '{print $2}')
          DEV_VERSION=$(grep "^version_dev:" version.txt | awk '{print $2}')

          if [ "$BRANCH" = "Automation" ]; then
            VERSION="$MAIN_VERSION"
          elif [ "$BRANCH" = "dev" ]; then
            VERSION="$DEV_VERSION"
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi

          echo "Using version: $VERSION"
          echo "tag=$VERSION" >> "$GITHUB_OUTPUT"
          echo "IMAGE_NAME=${{ env.REGISTRY }}/ibm-oss-support/app:$VERSION" >> "$GITHUB_ENV"

      - name: Write CA cert to file
        run: printf '%s' "${{ secrets.OCP_CA_CERT }}" > /tmp/ca.crt

      - name: Log in to OpenShift
        run: |
          oc login --server=${{ secrets.OCP_SERVER }} \
                   -u ${{ secrets.OCP_USERNAME }} \
                   -p ${{ secrets.OCP_PASSWORD }} \
                   --certificate-authority=/tmp/ca.crt

      - name: Login to registries
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | podman login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "${{ secrets.GHCR_PAT }}" | podman login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Set config
        id: config
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

          if [ "$BRANCH" = "dev" ]; then
            echo "namespace=test" >> "$GITHUB_OUTPUT"
            echo "deploy_path=${{ secrets.DEPLOY_PATH_DEV }}" >> "$GITHUB_OUTPUT"
          elif [ "$BRANCH" = "Automation" ] || [ "$BRANCH" = "Automation" ]; then
            echo "namespace=test" >> "$GITHUB_OUTPUT"
            echo "deploy_path=${{ secrets.DEPLOY_PATH_MAIN }}" >> "$GITHUB_OUTPUT"
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi

          echo "repo_path=${{ secrets.REPO_PATH }}" >> "$GITHUB_OUTPUT"

          
      - name: Build image
        run: |
          cd ${{ steps.config.outputs.repo_path }}
          podman build -t $IMAGE_NAME . > /tmp/build.log 2>&1 || {
            echo "Build failed:"
            cat /tmp/build.log
            exit 1
          }

      - name: Push image
        run: |
          podman push $IMAGE_NAME >> /tmp/push.log 2>&1 || {
            echo "Push failed"
            cat /tmp/push.log
            exit 1
          }
