name: Test Runner Connection

on:
  push:
    branches:
      - test-deployment

jobs:
  test-runner:
    runs-on: self-hosted  
    steps:
      - name: Show runner info
        run: |
          echo "Runner name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner labels: ${{ runner.labels }}"
          echo "Hostname: $(hostname)"

