name: Verify runner = worker4

on:
  push:
    branches:
      - test-deployment

jobs:
  verify-runner:
    runs-on: worker4
    timeout-minutes: 5

    steps:
      - name: Show runner info
        run: |
          echo "runner.name   = ${{ runner.name }}"
          echo "runner.os     = ${{ runner.os }}"
          echo "runner.arch   = ${{ runner.arch }}"
          echo "runner.labels = ${{ runner.labels }}"
          echo "hostname      = $(hostname)"
          echo "whoami        = $(whoami)"

      - name: Assert runner has 'worker4' label
        run: |
          echo "${{ runner.labels }}" | grep -qw worker4 || {
            echo "::error::This runner does not have 'worker4' label. Labels: ${{ runner.labels }}"
            exit 1
          }

      - name: Done
        run: |
          echo "Confirmed: running on a runner with label 'worker4'"
